# Dockerfile for Django backend
FROM python:3.11-slim

# Set environment variables for Python
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code

COPY requirements.txt /code/
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . /code/

# Collect static files
RUN python manage.py collectstatic --noinput

CMD ["gunicorn", "moodsy.wsgi:application", "--bind", "0.0.0.0:8000"]