# Generated by Django 5.2.1 on 2025-05-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('published_at', models.DateTimeField()),
                ('sentiment', models.CharField(max_length=16)),
                ('country', models.CharField(blank=True, max_length=8, null=True)),
                ('language', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
    ]
